# Generated by Django 4.1 on 2022-10-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0003_alter_dosen_alamatrumah_alter_dosen_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fakultas', models.IntegerField(max_length=50)),
                ('nama_fakultas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prodi', models.IntegerField(max_length=50)),
                ('nama_prodi', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='Fakultas',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='Prodi',
        ),
        migrations.AddField(
            model_name='dosen',
            name='id_fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faperta.fakultas'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='id_prodi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faperta.prodi'),
        ),
    ]
