# Generated by Django 4.1 on 2022-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0004_fakultas_prodi_remove_dosen_fakultas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultas',
            name='id_fakultas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prodi',
            name='id_prodi',
            field=models.IntegerField(),
        ),
    ]
